[tool.black]
line-length = 100
target-version = ["py311", "py312", "py313"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 100

[tool.flake8]
max-line-length = 160
extend-ignore = ["E203", "W503", "E402", "E741", "F811"]
exclude = ["*/migrations/*"]
