# Generated by Django 5.2.6 on 2025-09-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='otop_search_thailand.province')),
            ],
            options={
                'indexes': [models.Index(fields=['province', 'category'], name='otop_search_provinc_31acb1_idx'), models.Index(fields=['latitude', 'longitude'], name='otop_search_latitud_bd2e0c_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'province'), name='uniq_product_in_province')],
            },
        ),
    ]
